[project]
name = "volcnip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy==1.26.4",
    "obspy>=1.4.2",
    "scienceplots>=2.1.1",
]
